// Code generated by mockery. DO NOT EDIT.

package loanmocks

import (
	context "context"

	usecase "github.com/shandysiswandi/test-amartha/internal/loan/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockCreateNewLoan is an autogenerated mock type for the CreateNewLoan type
type MockCreateNewLoan struct {
	mock.Mock
}

type MockCreateNewLoan_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateNewLoan) EXPECT() *MockCreateNewLoan_Expecter {
	return &MockCreateNewLoan_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, in
func (_m *MockCreateNewLoan) Execute(ctx context.Context, in usecase.CreateProposedLoanInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateProposedLoanInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCreateNewLoan_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreateNewLoan_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.CreateNewLoanInput
func (_e *MockCreateNewLoan_Expecter) Execute(ctx interface{}, in interface{}) *MockCreateNewLoan_Execute_Call {
	return &MockCreateNewLoan_Execute_Call{Call: _e.mock.On("Execute", ctx, in)}
}

func (_c *MockCreateNewLoan_Execute_Call) Run(run func(ctx context.Context, in usecase.CreateProposedLoanInput)) *MockCreateNewLoan_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateProposedLoanInput))
	})
	return _c
}

func (_c *MockCreateNewLoan_Execute_Call) Return(_a0 error) *MockCreateNewLoan_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCreateNewLoan_Execute_Call) RunAndReturn(run func(context.Context, usecase.CreateProposedLoanInput) error) *MockCreateNewLoan_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateNewLoan creates a new instance of MockCreateNewLoan. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateNewLoan(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateNewLoan {
	mock := &MockCreateNewLoan{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
