with-expecter: true
disable-version-string: True
packages:
  github.com/shandysiswandi/test-amartha/internal/loan:
    config:
      all: True
      recursive: True
      outpkg: "loanmocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/loan/internal/mocks

  github.com/shandysiswandi/test-amartha/internal/pkg:
    config:
      all: True
      recursive: True
      outpkg: "pkgmocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      dir: internal/pkg/pkgmocks
